### ISSUE TITLE
Transfer repository to plone organization?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/five.customerize#18] opened 2022-07-01 06:16 UTC
In #17 the idea arose that this repository might only be relevant for Plone, so it could be moved over to the plone organization.

Who has to decide that?
What would be the process?

cc: @mauritsvanrees @esteele @dataflake

**Comment by dataflake** [comment] 2022-07-01 06:53
The process is simple: At the bottom of Settings | General there's a button "Transfer". Someone with the ability to create repositories within the plone organization (and presumably the ability to administer repositories in the zopefoundation organization) has to click that.

**Comment by davisagli** [comment] 2022-07-01 15:25
This idea makes some sense to me. five.customerize was designed to be usable outside of Plone, but as far as I'm aware it hasn't been widely used (even within Plone).

I am an admin in both organizations and can make the transfer but would like to hear confirmation from @mauritsvanrees or @esteele first.

The plone github organization is generally used for code owned by the Plone Foundation. Is there any formality needed with the foundation to transfer a repository there? I am guessing not, given that the Plone Foundation now has ownership of both codebases, right?

@mauritsvanrees I guess there is some update needed in buildout.coredev after the transfer, but github should redirect the old repository URL so it's not urgent.

**Comment by esteele** [comment] 2022-07-01 20:43
+1 from me. There should be no organizational blockers to moving it now that the foundations have merged.

**Comment by mauritsvanrees** [comment] 2022-07-01 22:42
+1 from me, but I wonder about legalities.

License is [ZPL](https://github.com/zopefoundation/five.customerize/blob/154df28d65a7def99f431ba82d0019744f2cc048/setup.py#L35), which is think is fine for Plone repositories.

Not all [contributors](https://github.com/zopefoundation/five.customerize/graphs/contributors) are part of the Plone GitHub organisation, though all are well known to us. Do they all need to agree with moving the code? I guess not, since the organisations have merged, so the Plone Foundation owns all Zope code already, even though it is in a different GitHub organisation.

Let me ping @jensens and @polyester from the Plone board for good measure.

**Comment by jensens** [comment] 2022-07-01 23:03
This is indeed something to be discussed by the board. Anyway, given both, Plone and Zope, IP is under the Plone Foundation I question if the move might be pointless. What is the core motivation for the move?

**Comment by dataflake** [comment] 2022-07-02 04:48
The core motivation is that Plone-only packages should be in the plone organization and managed by the Plone maintainers, not the Zope maintainers.

**Comment by jensens** [comment] 2022-07-21 19:14
At the board we think it is not worth the effort to transfer. Both repositories are under the Plone Foundation and @mauritsvanrees and @esteele our release managers have this on their radar.

**Comment by dataflake** [comment] 2022-07-21 20:38
OK, I will close this and @icemac and I will keep in mind that we don't need to invest time in this code.

**Closed by dataflake** 2022-07-21 20:38 UTC
Labels: question
